apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: s3vnl0jxg-go 
  janus-idp.io/tekton: s3vnl0jxg-go
  backstage.io/kubernetes-id: s3vnl0jxg-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: s3vnl0jxg-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml